### ISSUE TITLE
functional colors are ignored in scrollbar-color property value

### ISSUE THREAD

**Issue by phelipetls** [pascalduez/postcss-scrollbar#12]
The following file

```css
.scrollable {
  scrollbar-color: rgb(255,0,0) transparent;
}
```
gets converted into this:

```css
.scrollable::-webkit-scrollbar-thumb {
  background-color: transparent;
}
.scrollable::-webkit-scrollbar-track {
  background-color: transparent;
}
.scrollable::-webkit-scrollbar-corner {
  background-color: transparent;
}
.scrollable {
  scrollbar-color: rgb(255, 0, 0) transparent;
}
```

Which is unexpected to me.

By reading the [spec on `scrollbar-color`](https://drafts.csswg.org/css-scrollbars-1/#scrollbar-color), I got the impression that functional color notation should be allowed, since the [`<color>` type](https://drafts.csswg.org/css-scrollbars-1/#scrollbar-color) includes it.
